export { system, type System } from "./system.js"
export { type SystemPointer, type PointerEvents, type PointerPosition } from "./pointer.js"
export { type DesktopEvents, type DesktopSize, type SystemDesktop } from "./desktop.js"
export { context, type Context, type ContextServer } from "./context.js"
export { type Channel, type ChannelCapture, type ChannelEvents, type ChannelMessage } from "./channel.js"
export {
  ClientService,
  ServerService,
  Service,
  type ClientServiceChannel,
  type ServerServiceChannel,
  type ServiceChannel,
  type ServiceKey,
  type ServiceLifecycleEvents
} from "@phreshos/core"
export {
  Client,
  Endpoint,
  Process,
  Program,
  Server,
  type Window,
  type ProgramProcess,
  type AnswerCapture,
  type AnswerMessage,
  type AnswerObserver,
  type AskCapture,
  type AskMessage,
  type AskObserver,
  type ClientTraffic,
  type EndpointTraffic,
  type ServerTraffic,
  type TrafficCapture,
  type TrafficEvents,
  type TrafficMessage
} from "./domain.js"

export type {
  Askable,
  Capture,
  Captures,
  ClientDeclaration,
  Cleanup,
  DirectoryStat,
  EndpointDeclaration,
  EntryStat,
  EventMessage,
  EventName,
  EventObserver,
  EventOptions,
  EventSubscriber,
  Exit,
  FileStat,
  Launch,
  LaunchClient,
  Layer,
  LogKind,
  LogRecord,
  LogSource,
  Message,
  OtherStat,
  Outcome,
  PermissionDecision,
  Permission,
  Position,
  Storage,
  ProgramEvents,
  ProgramProcessEvents,
  ProgramProcessExit,
  ProgramSql,
  ProgramStore,
  ProcessEvents,
  Publishable,
  SystemUploads,
  Upload,
  Size,
  Subscribable,
  SubscribableEvents,
  SubscribableFallback,
  TimedAskable,
  TimedPermission,
  Timeoutable,
  Appearance,
  AppearanceEvents,
  AppearanceSource,
  AppearanceSurface,
  AnimationsPreference,
  DesktopPreferences,
  DesktopPreferencesEvents,
  DesktopPreferencesUpdate,
  SystemDesktopPreferences,
  ThemedValue,
  Theme,
  ThemePreference,
  Value,
  WindowEvents,
  WindowGeometry,
  WindowLayer,
  WindowState,
  Easing,
  LocalWindow,
  LocalWindowSurface,
  VisibilityTransition,
  Transaction
} from "@phreshos/core"
