export { system, type System } from "./system.js"
export { type SystemPointer, type PointerEvents, type PointerPosition } from "./pointer.js"
export { type DesktopEvents, type DesktopSize, type SystemDesktop } from "./desktop.js"
export {
  context,
  type Context,
  type ContextCapture,
  type ContextEvents,
  type ContextMessage,
  type ContextServer
} from "./context.js"
export {
  ClientService,
  ServerService,
  Service,
  type ServiceKey,
} from "@phreshos/core"
export {
  Client,
  Endpoint,
  Process,
  Program,
  Server,
  type Window,
  type ProgramProcess,
  type AnswerCapture,
  type AnswerMessage,
  type AnswerSubscriber,
  type AskCapture,
  type AskMessage,
  type AskSubscriber,
  type ClientTraffic,
  type EndpointTraffic,
  type ServerTraffic,
  type TrafficCapture,
  type TrafficEvents,
  type TrafficMessage
} from "./domain.js"

export type {
  Askable,
  Capture,
  Captures,
  CaptureSubscriber,
  ClientLaunch,
  ClientDeclaration,
  Cleanup,
  DirectoryStat,
  EndpointDeclaration,
  EndpointLifecycle,
  EndpointLifecycleEvents,
  EntryStat,
  EventMessage,
  EventName,
  EventOptions,
  EventSubscriber,
  Exit,
  FileStat,
  Launch,
  ServerLaunch,
  Layer,
  LogKind,
  LogRecord,
  LogSource,
  Message,
  OtherStat,
  Outcome,
  PermissionDecision,
  Permission,
  Position,
  Storage,
  ProgramEvents,
  ProgramProcessEvents,
  ProgramProcessExit,
  ProgramSql,
  ProgramStore,
  ProcessEvents,
  Publishable,
  SystemUploads,
  Upload,
  Size,
  Subscribable,
  SubscribableEvents,
  SubscribableFallback,
  TimedAskable,
  TimedPermission,
  Timeoutable,
  Appearance,
  AppearanceEvents,
  AppearanceSource,
  AppearanceSurface,
  AnimationsPreference,
  DesktopPreferences,
  DesktopPreferencesEvents,
  DesktopPreferencesUpdate,
  SystemDesktopPreferences,
  ThemedValue,
  Theme,
  ThemePreference,
  Value,
  WindowEvents,
  WindowGeometry,
  WindowLayer,
  WindowState,
  Easing,
  LocalWindow,
  LocalWindowSurface,
  VisibilityTransition,
  Transaction
} from "@phreshos/core"
